[cursor]
blink_interval = 750
vi_mode_style = "Beam"

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 16.0

[font.normal]
family = "mono"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 10000

[window]
decorations = "None"  # 禁用客户端装饰
dynamic_title = true
opacity = 1.00


[window.padding]
x = 20
y = 20

[general]
import = ["/home/clay/.config/alacritty/themes/snazzy.toml"]
